/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIndexRouteImport } from './routes/$category.index'
import { Route as CategoryBrandRouteImport } from './routes/$category.$brand'
import { Route as CategoryBrandProductRouteImport } from './routes/$category.$brand_.product'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryBrandRoute = CategoryBrandRouteImport.update({
  id: '/$category/$brand',
  path: '/$category/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryBrandProductRoute = CategoryBrandProductRouteImport.update({
  id: '/$category/$brand_/product',
  path: '/$category/$brand/product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/search': typeof SearchRoute
  '/$category/$brand': typeof CategoryBrandRoute
  '/$category/': typeof CategoryIndexRoute
  '/$category/$brand/product': typeof CategoryBrandProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/search': typeof SearchRoute
  '/$category/$brand': typeof CategoryBrandRoute
  '/$category': typeof CategoryIndexRoute
  '/$category/$brand/product': typeof CategoryBrandProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/search': typeof SearchRoute
  '/$category/$brand': typeof CategoryBrandRoute
  '/$category/': typeof CategoryIndexRoute
  '/$category/$brand_/product': typeof CategoryBrandProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/search'
    | '/$category/$brand'
    | '/$category/'
    | '/$category/$brand/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/search'
    | '/$category/$brand'
    | '/$category'
    | '/$category/$brand/product'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/search'
    | '/$category/$brand'
    | '/$category/'
    | '/$category/$brand_/product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  SearchRoute: typeof SearchRoute
  CategoryBrandRoute: typeof CategoryBrandRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  CategoryBrandProductRoute: typeof CategoryBrandProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/$category'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$brand': {
      id: '/$category/$brand'
      path: '/$category/$brand'
      fullPath: '/$category/$brand'
      preLoaderRoute: typeof CategoryBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$brand_/product': {
      id: '/$category/$brand_/product'
      path: '/$category/$brand/product'
      fullPath: '/$category/$brand/product'
      preLoaderRoute: typeof CategoryBrandProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  SearchRoute: SearchRoute,
  CategoryBrandRoute: CategoryBrandRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  CategoryBrandProductRoute: CategoryBrandProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
